/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#0d631b',
        'primary-container': '#2e7d32',
        'primary-fixed': '#a3f69c',
        'primary-fixed-dim': '#88d982',
        'on-primary': '#ffffff',
        'on-primary-container': '#cbffc2',
        'on-primary-fixed': '#002204',
        'on-primary-fixed-variant': '#005312',
        secondary: '#0058bc',
        'secondary-container': '#0070eb',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'on-secondary-fixed': '#001a41',
        'on-secondary-fixed-variant': '#004493',
        tertiary: '#814700',
        'tertiary-container': '#a45b00',
        'tertiary-fixed': '#ffdcc1',
        'tertiary-fixed-dim': '#ffb778',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffeee2',
        'on-tertiary-fixed': '#2e1500',
        'on-tertiary-fixed-variant': '#6c3a00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8faf8',
        'on-background': '#191c1b',
        surface: '#f8faf8',
        'surface-bright': '#f8faf8',
        'surface-dim': '#d8dad9',
        'surface-variant': '#e1e3e1',
        'surface-tint': '#1b6d24',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f2',
        'surface-container': '#eceeec',
        'surface-container-high': '#e6e9e7',
        'surface-container-highest': '#e1e3e1',
        'on-surface': '#191c1b',
        'on-surface-variant': '#40493d',
        outline: '#707a6c',
        'outline-variant': '#bfcaba',
        'inverse-primary': '#88d982',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1ef',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.97)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.35s ease-out forwards',
        'scale-in': 'scale-in 0.3s ease-out forwards',
      },
    },
  },
  plugins: [],
};
